apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: LOGGING_LEVEL
              value: "{{ .Values.logs.level }}"
            - name: BROKER_ADDRESS
              value: {{ .Values.broker.address }} 
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /livez
              port: 8080
          # readinessProbe:
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   httpGet:
          #     path: /readyz
          #     port: 8080
