### Variables

# Name
name: jobcreator

# Logs
logs:
  # Level
  level: "INFO"

# Replicas
replicas: 1

# Resources
resources:
  # Requests
  requests:
    # CPU
    cpu: 20m
    # Memory
    memory: 50Mi
  # Limits
  limits:
    # CPU
    cpu: 800m
    # Memory
    memory: 1000Mi

# Broker
broker:
  # Address
  address: "kafka.platform.svc.cluster.local:9092"
  # Topic
  topic: "jobs"
  # Consumer group
  consumerGroup: "jobcreator"

# Cache
cache:
  # Address
  addresses:
    # Master
    master: "redis-master.platform.svc.cluster.local"
  # Port
  port: 6379
  # Password
  password: "megasecret"
